const $=s=>document.querySelector(s),V=()=>$('#view');
let timer=null;
function setTheme(t){document.documentElement.dataset.theme=t;P.s.theme=t;P.save()}
function setCalm(c){P.s.calm=c;document.body.classList.toggle('calm',c);$('#calmBtn').setAttribute('aria-pressed',c);P.save()}
function route(){clearInterval(timer);const [,page,arg]=(location.hash||'#/home').split('/');({home,map,lesson:()=>lesson(arg),trainer,profile}[page]||home)();P.head();V().focus();scrollTo(0,0)}
function home(){const p=Math.round(Object.keys(P.s.done).length/TOPICS.length*100);V().innerHTML='<section class="hero"><div class="scene"><div class="cube">x²</div></div><h1>Математика с нуля — <span>до уверенности</span></h1><p>Курс для студентов колледжа, которые не учились в школе.</p><div class="cta"><a class="btn" href="#/lesson/'+TOPICS[0].id+'">Начать учиться</a><a class="btn ghost" href="#/map">Программа курса</a></div></section><div class="card"><b>Твой прогресс: '+p+'%</b><div class="prog"><i style="width:'+p+'%"></i></div></div><div class="card"><h2>Как это работает</h2><p>Короткие уроки, мгновенная проверка, XP и тренажёр.</p><p class="hint">Факт дня: '+M.fact()+'</p></div>';M.say('happy',M.hello())}
function map(){const nxt=TOPICS.find(t=>!P.s.done[t.id]);V().innerHTML='<h1>Карта курса</h1>'+MODULES.map((m,i)=>{const ts=TOPICS.filter(t=>t.module===i);return'<div class="mod">'+i+'. '+m+'</div><div class="nodes">'+(ts.length?ts.map(t=>'<a class="node '+(P.s.done[t.id]?'done':nxt&&nxt.id===t.id?'cur':'')+'" href="#/lesson/'+t.id+'">'+(P.s.done[t.id]?'✓ ':'')+t.title+'</a>').join(''):'<span class="node">скоро</span>')+'</div>'}).join('')}
function lesson(id){const t=TOPICS.find(x=>x.id===id);if(!t)return home();const S=['<h2>Зачем это нужно</h2><p>'+t.hook+'</p>'];t.theory.forEach(s=>S.push('<h2>'+s.h+'</h2><p>'+s.t+'</p>'));if(t.viz==='disc')S.push('<h2>Попробуй сам</h2><p>Двигай ползунки и смотри на D.</p>'+['a','b','c'].map(k=>'<label>'+k+' = <b id="v'+k+'">1</b><input type="range" min="-5" max="5" value="1" id="r'+k+'" oninput="disc()"></label>').join('')+'<p id="dres" class="big"></p>');S.push('<h2>Проверь себя</h2>'+t.quiz.map(q=>'<div class="q"><p>'+q.q+'</p>'+q.o.map((o,i)=>'<button class="opt" onclick="Q.pick(this,'+(i===q.a)+','+JSON.stringify(q.e)+')">'+o+'</button>').join('')+'<p class="fb"></p></div>').join(''));S.push('<h2>Практика</h2>'+t.tasks.map((k,i)=>'<div class="q"><p>'+k.l+' '+k.q+'</p><input type="number" step="any"> <button class="btn sm" onclick="Q.task(this,'+JSON.stringify(t.id)+','+i+')">Проверить</button> <button class="btn ghost sm" onclick="Q.hint(this,'+JSON.stringify(t.id)+','+i+')">Подсказка</button><p class="fb"></p></div>').join(''));S.push('<h2>Итог</h2>'+t.summary.map(x=>'<p>✅ '+x+'</p>').join('')+'<p class="big">+'+t.xp+' XP</p>');let i=0;function show(){V().innerHTML='<div class="prog"><i style="width:'+((i+1)/S.length*100)+'%"></i></div><section class="card">'+S[i]+'</section><div class="nav"><button class="btn ghost" id="pv" '+(i?'':'disabled')+'>←</button><button class="btn" id="nx">'+(i===S.length-1?'Завершить урок':'Дальше')+'</button></div>';if($('#dres'))disc();$('#pv').onclick=()=>{i--;show()};$('#nx').onclick=()=>{if(i<S.length-1){i++;show()}else{if(P.finish(t.id))P.add(t.xp);FX.confetti();M.say('cheer','Урок пройден!');location.hash='#/map'}}}show()}
function disc(){const [a,b,c]=['a','b','c'].map(k=>{const v=+$('#r'+k).value;$('#v'+k).textContent=v;return v});const D=b*b-4*a*c;$('#dres').textContent=a===0?'a=0 — это не квадратное уравнение':'D = '+D+' → '+(D>0?'два корня':D===0?'один корень':'корней нет')}
function trainer(){let cur,combo=0,score=0,left=0,best=+localStorage.getItem('matstartBest')||0;V().innerHTML='<h1>Тренажёр</h1><div class="card"><p id="st">Серия: 0</p><p class="big" id="tq"></p><input type="number" id="ta"> <button class="btn sm" id="tg">Ответить</button> <button class="btn ghost sm" id="t60">60 секунд</button><p class="fb" id="tf"></p><p id="tt">Рекорд: '+best+'</p></div>';const next=()=>{cur=GEN[Math.floor(Math.random()*GEN.length)]();$('#tq').textContent=cur.q;$('#ta').value='';$('#ta').focus()};const upd=()=>$('#st').textContent='Серия: '+combo+' | Верно: '+score;const go=()=>{if($('#ta').value==='')return;if(+$('#ta').value===cur.a){combo++;score++;P.add(2);$('#tf').textContent='Верно!';if(combo%5===0)M.win()}else{combo=0;$('#tf').textContent='Правильно: '+cur.a;M.oops()}upd();next()};$('#tg').onclick=go;$('#ta').onkeydown=e=>{if(e.key==='Enter')go()};$('#t60').onclick=()=>{score=0;combo=0;left=60;next();clearInterval(timer);timer=setInterval(()=>{left--;$('#tt').textContent='Осталось: '+left+' c';if(left<=0){clearInterval(timer);$('#tt').textContent='Время! Верно: '+score}},1000)};next()}
function profile(){const s=P.s,i=P.lvl();V().innerHTML='<h1>Профиль</h1><div class="card"><p class="big">'+P.LV[i]+'</p><p>'+s.xp+' XP · решено задач: '+s.tasks+'</p><p>Пройдено уроков: '+Object.keys(s.done).length+' из '+TOPICS.length+'</p></div><div class="card"><button class="btn sm" onclick="P.exp()">Экспорт</button> <button class="btn ghost sm" onclick="P.reset()">Сбросить</button></div>'}
document.addEventListener('DOMContentLoaded',()=>{setTheme(P.s.theme||(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'));setCalm(P.s.calm);$('#themeBtn').onclick=()=>setTheme(P.s.theme==='dark'?'light':'dark');$('#calmBtn').onclick=()=>setCalm(!P.s.calm);addEventListener('hashchange',route);route();if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js').catch(()=>{})});